### ISSUE TITLE
Allow configuring `tqdm` generator

### ISSUE THREAD

**Issue by edgarrmondragon** [dbt-labs/jaffle-shop-generator#110]
### 🐛 Describe the bug

By default, the `tqdm` library produces non-ascii characters:

```
[SIM]: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 365/365 [00:00<00:00, 393.21it/s]
```

There's an [`ascii` option](https://tqdm.github.io/docs/tqdm/#format_meter), which could be passed from `Simulation.run_simulation`:

https://github.com/dbt-labs/jaffle-shop-generator/blob/0806cb627139238225503f019af042e4aa39f92e/jafgen/simulation.py#L95-L97

```diff
-     def run_simulation(self):
- 
-         for i in tqdm(range(self.sim_days), desc="[SIM]"):
+     def run_simulation(self, **kwargs):
+  
+         for i in tqdm(range(self.sim_days), desc="[SIM]", **kwargs):
```

This would allow the caller to do this

```python
sim = Simulation(years=1)
sim.run_simulation(ascii=True)
```

which produces

```
SIM]: 100%|###########################################################################################| 365/365 [00:00<00:00, 398.92it/s]
```

### Versions

Python 3.11.6
Faker==15.3.4
-e git+https://github.com/dbt-labs/jaffle-shop-generator.git@0806cb627139238225503f019af042e4aa39f92e#egg=jafgen
numpy==1.24.0
pandas==1.5.2
python-dateutil==2.8.2
pytz==2023.3.post1
six==1.16.0
tqdm==4.64.1

**Comment by edgarrmondragon** [comment]
Ah, this should've been a feature request 😬😅

**Comment by gwenwindflower** [comment]
hey @edgarrmondragon this has been mostly an ignored side project, i'm doing some work to get the repo in shape for continued use. in that work i refactored the CLI to use `typer` which relies on Rich's `Progress` module to provide the progress bars and I think should fix this.

**Comment by edgarrmondragon** [comment]
@gwenwindflower thanks for circling back and giving some love to the repo!
